import CompanionPanel from "./CompanionPanel";
import HeroPanel from "./HeroPanel";
import QuestPanel from "./QuestPanel";
import TimerPanel from "./TimerPanel";

function DashboardView({
  subjectPresets,
  state,
  activeSubject,
  levelFlash,
  onSwitchSubject,
  rewardToast,
  newQuestTitle,
  newQuestDifficulty,
  newTemplateTitle,
  newTemplateType,
  newTemplateDifficulty,
  revisionQueue,
  onCompleteQuest,
  onSetNewQuestTitle,
  onSetNewQuestDifficulty,
  onAddCustomQuest,
  onRegenerateQuests,
  onToggleAmbientAudio,
  onResolveRevision,
  getReviewUrgency,
  onSetNewTemplateTitle,
  onSetNewTemplateType,
  onSetNewTemplateDifficulty,
  onAddTemplate,
  manaPercent,
  partyContribution,
  partyPercent,
  goalPercent,
  goalLabel,
  goalSessions,
  formatTime,
  onToggleTimer,
  onResetTimer,
  onSaveGoal,
  onSetGoalLabel,
  onSetGoalSessions,
  semesterDeadline,
  onSetTimerPreset,
  petCelebrating,
  showSettings,
  currentTheme,
  prestigeThemeChoices,
  importFileRef,
  journalPreview,
  journalPrompt,
  reflectionText,
  prestigeEligible,
  streak,
  noteText,
  dailyQuote,
  dailyTip,
  onToggleSound,
  onToggleSettings,
  onUpdateSetting,
  onToggleNotifications,
  onChangeTheme,
  onExportBackup,
  onImportBackup,
  onSetReflectionText,
  onAddReflection,
  onUpdateNote,
  shopItems,
  onBuyShopItem,
  onApplyPrestige,
  battle,
  partyRoster,
}) {
  return (
    <>
      <HeroPanel
        subjectPresets={subjectPresets}
        subjects={state.subjects}
        activeSubjectKey={state.activeSubject}
        activeSubject={activeSubject}
        event={state.event}
        guild={state.guild}
        levelFlash={levelFlash}
        dailyQuote={dailyQuote}
        dailyTip={dailyTip}
        onSwitchSubject={onSwitchSubject}
      />

      <section className="dashboard-grid">
        <QuestPanel
          activeSubject={activeSubject}
          dayKey={state.dayKey}
          event={state.event}
          rewardToast={rewardToast}
          newQuestTitle={newQuestTitle}
          newQuestDifficulty={newQuestDifficulty}
          newTemplateTitle={newTemplateTitle}
          newTemplateType={newTemplateType}
          newTemplateDifficulty={newTemplateDifficulty}
          revisionQueue={revisionQueue}
          ambientEnabled={state.settings.ambientEnabled}
          ambientMode={state.settings.ambientMode}
          onCompleteQuest={onCompleteQuest}
          onSetNewQuestTitle={onSetNewQuestTitle}
          onSetNewQuestDifficulty={onSetNewQuestDifficulty}
          onAddCustomQuest={onAddCustomQuest}
          onRegenerateQuests={onRegenerateQuests}
          onToggleAmbientAudio={onToggleAmbientAudio}
          onResolveRevision={onResolveRevision}
          getReviewUrgency={getReviewUrgency}
          onSetNewTemplateTitle={onSetNewTemplateTitle}
          battle={battle}
          party={partyRoster}
          profile={state.profile}
          onSetNewTemplateType={onSetNewTemplateType}
          onSetNewTemplateDifficulty={onSetNewTemplateDifficulty}
          onAddTemplate={onAddTemplate}
        />

        <TimerPanel
          timer={state.timer}
          manaPercent={manaPercent}
          activeSubject={activeSubject}
          party={state.party}
          partyContribution={partyContribution}
          partyPercent={partyPercent}
          goalPercent={goalPercent}
          goalLabel={goalLabel}
          goalSessions={goalSessions}
          formatTime={formatTime}
          onToggleTimer={onToggleTimer}
          onResetTimer={onResetTimer}
          onSaveGoal={onSaveGoal}
          onSetGoalLabel={onSetGoalLabel}
          onSetGoalSessions={onSetGoalSessions}
          semesterDeadline={semesterDeadline}
          onSetTimerPreset={onSetTimerPreset}
        />

        <CompanionPanel
          activeSubject={activeSubject}
          petCelebrating={petCelebrating}
          showSettings={showSettings}
          settings={state.settings}
          currentTheme={currentTheme}
          prestigeThemeChoices={prestigeThemeChoices}
          importFileRef={importFileRef}
          journalPreview={journalPreview}
          journalPrompt={journalPrompt}
          reflectionText={reflectionText}
          prestigeEligible={prestigeEligible}
          streak={streak}
          noteText={noteText}
          guild={state.guild}
          onToggleSound={onToggleSound}
          onToggleSettings={onToggleSettings}
          onUpdateSetting={onUpdateSetting}
          onToggleNotifications={onToggleNotifications}
          onToggleAmbientAudio={onToggleAmbientAudio}
          onChangeTheme={onChangeTheme}
          onExportBackup={onExportBackup}
          onImportBackup={onImportBackup}
          onSetReflectionText={onSetReflectionText}
          onAddReflection={onAddReflection}
          onUpdateNote={onUpdateNote}
          shopItems={shopItems}
          onBuyShopItem={onBuyShopItem}
          onApplyPrestige={onApplyPrestige}
        />
      </section>
    </>
  );
}

export default DashboardView;
